#############################################################################
# Makefile for building: Kutter
# Generated by qmake (3.1) (Qt 5.12.10)
# Project:  Kutter.pro
# Template: app
# Command: C:\Qt\Static\qtbase\bin\qmake.exe -o Makefile Kutter.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\Static\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Static\qtbase\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Static\qtbase\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Kutter.pro ../../../../Qt/Static/qtbase/mkspecs/win32-g++/qmake.conf ../../../../Qt/Static/qtbase/mkspecs/features/spec_pre.prf \
		../../../../Qt/Static/qtbase/mkspecs/qdevice.pri \
		../../../../Qt/Static/qtbase/mkspecs/features/device_config.prf \
		../../../../Qt/Static/qtbase/mkspecs/common/sanitize.conf \
		../../../../Qt/Static/qtbase/mkspecs/common/gcc-base.conf \
		../../../../Qt/Static/qtbase/mkspecs/common/g++-base.conf \
		../../../../Qt/Static/qtbase/mkspecs/common/angle.conf \
		../../../../Qt/Static/qtbase/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../../Qt/Static/qtbase/mkspecs/common/windows-vulkan.conf \
		../../../../Qt/Static/qtbase/mkspecs/common/g++-win32.conf \
		../../../../Qt/Static/qtbase/mkspecs/qconfig.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_dbus.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_windowsuiautomation_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qdirect2d.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qdirect2d.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qsqlodbc.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qwindows.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qwindowsvistastyle.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qxdgdesktopportal.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_windowsprintersupport.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qfloat16-tables.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../../Qt/Static/qtbase/mkspecs/features/qt_functions.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/qt_config.prf \
		../../../../Qt/Static/qtbase/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/Static/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/Static/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/toolchain.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/default_pre.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/resolve_config.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/default_post.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/precompile_header.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/warn_on.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/qt.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/resources.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/moc.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/win32/opengl.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/uic.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/qmake_use.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/file_copies.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/win32/windows.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/testcase_targets.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/exceptions.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/yacc.prf \
		../../../../Qt/Static/qtbase/mkspecs/features/lex.prf \
		Kutter.pro \
		../../../../Qt/Static/qtbase/lib/Qt5Widgets.prl \
		../../../../Qt/Static/qtbase/lib/Qt5Gui.prl \
		../../../../Qt/Static/qtbase/lib/Qt5Core.prl \
		../../../../Qt/Static/qtbase/lib/qtmain.prl
	$(QMAKE) -o Makefile Kutter.pro -config release
../../../../Qt/Static/qtbase/mkspecs/features/spec_pre.prf:
../../../../Qt/Static/qtbase/mkspecs/qdevice.pri:
../../../../Qt/Static/qtbase/mkspecs/features/device_config.prf:
../../../../Qt/Static/qtbase/mkspecs/common/sanitize.conf:
../../../../Qt/Static/qtbase/mkspecs/common/gcc-base.conf:
../../../../Qt/Static/qtbase/mkspecs/common/g++-base.conf:
../../../../Qt/Static/qtbase/mkspecs/common/angle.conf:
../../../../Qt/Static/qtbase/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../../Qt/Static/qtbase/mkspecs/common/windows-vulkan.conf:
../../../../Qt/Static/qtbase/mkspecs/common/g++-win32.conf:
../../../../Qt/Static/qtbase/mkspecs/qconfig.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_libpng.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_core.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_dbus.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_gui.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_network.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_sql.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_windowsuiautomation_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_xml.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qdirect2d.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qdirect2d.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qsqlodbc.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qwindows.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qwindows.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qwindowsvistastyle.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_qxdgdesktopportal.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../../../Qt/Static/qtbase/mkspecs/modules-inst/qt_plugin_windowsprintersupport.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_moc.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qfloat16-tables.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_qvkgen.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_rcc.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../../../Qt/Static/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../../../Qt/Static/qtbase/mkspecs/features/qt_functions.prf:
../../../../Qt/Static/qtbase/mkspecs/features/qt_config.prf:
../../../../Qt/Static/qtbase/mkspecs/win32-g++/qmake.conf:
../../../../Qt/Static/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/Static/qtbase/mkspecs/features/exclusive_builds.prf:
../../../../Qt/Static/qtbase/mkspecs/features/toolchain.prf:
../../../../Qt/Static/qtbase/mkspecs/features/default_pre.prf:
../../../../Qt/Static/qtbase/mkspecs/features/win32/default_pre.prf:
../../../../Qt/Static/qtbase/mkspecs/features/resolve_config.prf:
../../../../Qt/Static/qtbase/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/Static/qtbase/mkspecs/features/default_post.prf:
../../../../Qt/Static/qtbase/mkspecs/features/precompile_header.prf:
../../../../Qt/Static/qtbase/mkspecs/features/warn_on.prf:
../../../../Qt/Static/qtbase/mkspecs/features/qt.prf:
../../../../Qt/Static/qtbase/mkspecs/features/resources.prf:
../../../../Qt/Static/qtbase/mkspecs/features/moc.prf:
../../../../Qt/Static/qtbase/mkspecs/features/win32/opengl.prf:
../../../../Qt/Static/qtbase/mkspecs/features/uic.prf:
../../../../Qt/Static/qtbase/mkspecs/features/qmake_use.prf:
../../../../Qt/Static/qtbase/mkspecs/features/file_copies.prf:
../../../../Qt/Static/qtbase/mkspecs/features/win32/windows.prf:
../../../../Qt/Static/qtbase/mkspecs/features/testcase_targets.prf:
../../../../Qt/Static/qtbase/mkspecs/features/exceptions.prf:
../../../../Qt/Static/qtbase/mkspecs/features/yacc.prf:
../../../../Qt/Static/qtbase/mkspecs/features/lex.prf:
Kutter.pro:
../../../../Qt/Static/qtbase/lib/Qt5Widgets.prl:
../../../../Qt/Static/qtbase/lib/Qt5Gui.prl:
../../../../Qt/Static/qtbase/lib/Qt5Core.prl:
../../../../Qt/Static/qtbase/lib/qtmain.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Kutter.pro -config release

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\Zenger\Documents\Kutter\uic_wrapper.bat C:\Users\Zenger\Documents\Kutter\uic_wrapper.bat .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
